### ISSUE TITLE
Resource estimation fails for Deutsch-Josza (Advanced) sample

### ISSUE THREAD

**Issue by minestarks** [microsoft/qsharp#1157]
1. Go to https://vscode.dev/quantum/playground/
2. Open the Deutsch-Jozsa (Advanced).qs sample
3. Run the "Calculate Resource Estimates" command

Error:
![image](https://github.com/microsoft/qsharp/assets/16928427/1a9c7dc7-9db0-4de2-809c-7ae535445e80)

> Command 'Q#: Calculate Resource Estimates' resulted in an error
Estimating failed with error: program failed: SimpleConstantBoolF should be detected as constant

Running the program works fine.

**Comment by swernli** [comment]
This is expected and is a side effect of writing samples that are expressly for simulation. Because resource estimation does not perform any quantum simulation, it always returns measurement results with a 50/50 likelihood of `One` or `Zero` using a fixed seed. This means that programs like this sample that try to verify the quantum calculation was correct will fail because the results they get back from measurement are random noise. So, for the most part, anything with the `(Advanced)` label in its name is not expected to work with resource estimation. Meanwhile, some of the samples that are explicitly designed for resource estimation (and have `(Resource Estimation)` in their label) are too big to simulate. A good rule of thumb would be that anything that is compatible with the base profile does not depend on branching due to measurement result and would be safe to resource estimate.
