### ISSUE TITLE
IntelliSense error highlighting on one issue blocked by presence of another, in a different operation or later in the same operation

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/qsharp#1869]
**Describe the bug**

Incorrect qubit allocation error and type error seem to block "operation does not support the adjoint functor" error, even if they're in other callables than that one. This looks odd; I suspect they're generated on different compilation passes, but it would be really nice to get all of them at once, since neither of errors affected the lack of adjoint factor in this one.

**To Reproduce**

```qsharp
operation ApplyMarkingOracleAsPhaseOracle (
    markingOracle : ((Qubit[], Qubit) => Unit), 
    inputRegister : Qubit[]
) : Unit {
    use target = Qubit(1);
}

operation IsFunctionConstant (nQubits : Int, phaseOracle : (Qubit[] => Unit)) : Bool {
    mutable isConstant = true;
    use qubits = Qubit[nQubits];
    // Apply the H gates, the oracle and the H gates again
    within {
        ApplyToEach(H, qubits);
    } apply {
        phaseOracle(qubits);
    }
    // Measure all qubits
    let measurementResults = M(qubits);
    for m in measurementResults {
        if m == Zero {
            set isConstant = false;
        }
    }
    return isConstant;
}
```

**Expected behavior**

Each error highlighted independently, with errors in one operation not blocking errors in other operations.

**Screenshots**

With first error in place - second error is not highlighted, but the third one is highlighted.
![image](https://github.com/user-attachments/assets/5226ce4a-a739-48be-8b0e-189d2040edaa)

With the first error fixed, only the third one is highlighted.
![image](https://github.com/user-attachments/assets/88d3256f-d047-4f6e-9342-dc7fe5ec8534)

Only with the first and the third error both fixed the second one is highlighted
![image](https://github.com/user-attachments/assets/ce84e861-0aea-4d70-9452-bff0efc15542)

**System information**

- AQDK 1.7.0

**Comment by sezna** [comment]
This is unfortunately something that's not possible to address, and it is because of the nature of compiler phases. The compiler have phases -- first it parses, then we type check, produce some intermediate representations, and then run passes. Generally, prior phases have to complete before the next phase begins, and this is true of most languages. If we passed malformed phase output to the next phase, there would be lots of nonsensical errors produced in addition to the one that you're wanting to see.

I don't think this is something we can fix, although do know that we do try to recover from errors where possible to mitigate this. It just isn't possible _in general_.
