### ISSUE TITLE
Hierarchical Namespaces

### ISSUE THREAD

**Issue by bamarsha** [microsoft/qsharp#493]
Namespaces don't make sense in Q#. Their only benefit is in organization and avoiding name conflicts, but they don't help you define abstractions or use encapsulation/information hiding. A module system does a better job at organization than namespaces and is also a good unit of abstraction. Namespaces should be deprecated and replaced with modules.

**Comment by samarsha** [comment]
I don't think flat vs. hierarchical is the main problem with Q#'s namespace system. For me, the major issue is that namespaces are *open* instead of *closed*, meaning that a namespace can be defined multiple times, and the items in the namespace are the union of the items in all partial namespaces with the same name. This is related to *internal* being the lowest visibility in Q#, which is too coarse. A *private* visibility is needed but can't be meaningfully defined without a closed unit of abstraction.

I didn't see this mentioned explicitly in the new design, but it seems like because there is a one-to-one mapping from files to namespaces, namespaces are implicitly closed because there can only be one file at a given path. If so, it looks like this is circumvented by explicit namespace definitions which are still supported. I would argue that *private by default* is much better than *internal by default* so while this is an improvement, I don't think it goes far enough.

While making each file implicitly declare its own namespace is a good idea, it looks like this design also has each file be *at most* one namespace, because explicit namespace definitions are treated as a backwards compatibility feature. This seems like an unnecessary limitation. It's another factor that encourages too coarse-grained units of abstraction, because it's easier to put more definitions in the same namespace than to create a new file.

I'm also wondering what is truly *hierarchical* about this design? For example, does `Foo/Bar.qs` in namespace `Foo.Bar` automatically import items from `Foo.qs` in namespace `Foo`? Can `Foo.Bar` import from `Foo.Baz` using a relative path like `super.Baz`? Is there a visibility modifier for items that can be seen by parent or child namespaces but not by sibling namespaces? I didn't see any of these mentioned.
