### ISSUE TITLE
Error in MultiQubitDumpMachineDemo Code

### ISSUE THREAD

**Issue by b-goldsmith** [microsoft/qsharp#763]
**Describe the bug**

In the tutorials, The Qubit > Display the Quantum State of a Multi-Qubit Program includes the demo code DumpMachine for Multi-Qubit Systems. The comments about performing the X gate on the second qubit are incorrect:
![image](https://github.com/microsoft/qsharp/assets/62308289/0d87c1c9-449b-45cf-a76a-7e93edec118d)

First of all, the entire system is now in state |10> and also it is decimal notation that represents |2>. Finally, the Message() should also be changed to |10>. 

This would be extremely confusing to someone who is new to quantum computing, especially if they run the code and see:
![image](https://github.com/microsoft/qsharp/assets/62308289/076ae0d4-e43c-4f64-9538-6d4adc1c0858)

**To Reproduce**

1. Go to the Learn with Azure Quantum katas and navigate to The Qubit then Display the Quantum State of a Multi-Qubit Program.
2. Copy the demo code and run it.
3. See confusing/conflicting results.

**Expected behavior**

I would expect the comment in the code to read:
The entire system is now in state |10>, or, in decimal notation, |2>.

Then the Message("State |01>:"); would be changed to Message(State |10>:");

**Screenshots**
Current implementation:
![image](https://github.com/microsoft/qsharp/assets/62308289/0d87c1c9-449b-45cf-a76a-7e93edec118d)

Results from running the demo:
![image](https://github.com/microsoft/qsharp/assets/62308289/076ae0d4-e43c-4f64-9538-6d4adc1c0858)

**System information**

N/A

**Additional context**

I would be happy to correct this issue if you would like to assign it to me.

**Comment by tcNickolas** [comment]
This is an artifact of migration from the "old" QDK used in https://github.com/microsoft/QuantumKatas/ to the new QDK we're using on the website (see https://devblogs.microsoft.com/qsharp/introducing-the-azure-quantum-development-kit-preview/ for the announcement). Old QDK had a different output format for DumpMachine, so the same code would output 
![image](https://github.com/microsoft/qsharp/assets/10113024/83f6df71-296c-4fcf-bf34-1d85311a94c9)
(You can see that basis states are by default collapsed into integers, using little-endian notation, so the state 2 corresponded to a 01 bit string indeed - that's why the comment mentioned little endian. The new DumpMachine also uses a different order of bits, qubit 0 is printed last, so the bit string for this state would be indeed 10, but still 2 in big-endian.)

More broadly, the tutorials migrated to the website need to be double-checked for the discrepancies between the descriptions and the code output that arise from endianness - for example, the same issue is likely to show up in the MultiQubitSystems tutorial.

Thank you for reporting this!

**Comment by bdg221** [comment]
This same behavior can be seen in the MultiQubitSystemsDemo code from Multi-Qubit Systems > Multi-Qubit Systems in Q#.

![image](https://github.com/microsoft/qsharp/assets/62308289/d9ebb388-1bb8-4d37-ad3a-a20c3b632693)

![image](https://github.com/microsoft/qsharp/assets/62308289/2f9d76d4-f82e-42c1-84f5-f16b6fe508e0)

![image](https://github.com/microsoft/qsharp/assets/62308289/e5d30986-34a0-43f6-8624-4bbd4ae9b7ad)

![image](https://github.com/microsoft/qsharp/assets/62308289/179cdc34-a749-440b-b151-f3ed9d77959f)

**Comment by DmitryVasilevsky** [comment]
With changes https://github.com/microsoft/qsharp/pull/1079, https://github.com/microsoft/qsharp/pull/1162 and https://github.com/microsoft/qsharp/pull/1169 this issue should be fixed in the repository. This bug should be fixed once these changes propagate to QCOM web site.

**Comment by minestarks** [comment]
@DmitryVasilevsky  can this be closed now? I wasn't sure where to check on QCOM

**Comment by tcNickolas** [comment]
This shows up in Multi-Qubit Systems kata, `MultiQubitSystemsDemo` demo. I've checked that the output matches the statements in the message on QCOM, so we can close this. 

(And thank you @bdg221 for the original report!)
