### ISSUE TITLE
Build and release process

### ISSUE THREAD

**Issue by billti** [microsoft/qsharp#8]
This issue is to discuss how we build & release the bits this repo contains. Topics include release pipelines, security requirements (e.g. code scanning, signing, etc.), if/when we branch for release, release schedule, if/how we will support multiple release "channels" (e.g. official, beta, nightly, etc.), the distribution mechanisms (e.g., npm, pip, VS Code marketplace, GitHub releases, etc.), and so forth.

I expect this to be a long running issue as we iterate and adapt over time.

Proposals and discussion to follow...

**Comment by billti** [comment]
OK. Here's the proposal.

- For our release artifacts (which initially are a VS Code extension and some pip packages), we'll ship to 3 separate channels. A `<name>-nightly`, a `<name>-preview`, and a `<name>` channel, which we'll refer to as the nightly, preview, and stable channels, respectively.
- Nightly will get published every night from the 'main' branch. The expectation is that engineering will be using this branch for daily work to catch regressions early, or partners/customers can use it after a feature is merged to verify early.
- As we start to stabilize an upcoming release, we'll branch for it and push releases to the `preview` channel for testing and early adopters.
- When a release is ready, we'll push to the stable channel, which is where the vast majority of customers will pick it up.

We'll assume a monthly release schedule, aiming for roughly the middle of each month (this avoids most holidays which are typically start or end of month). To stabilize once features are done, we'll create a branch named `release/YYMM` for the target release month, e.g. for September 2023 release we'll create `release/2309`. Only fixes should go in to a release branch, and be ported to 'main'.

We'll avoid using pre-release semantics in versions (e.g. 1.10.1-beta). If you install from a pre-release channel, that should be obvious and intended. We'll simply version with the major version being `1` (only incrementing when we make changes worthy of a major version bump - we can argue about semver later :-) ), the minor version being the YYMMDD date, and the patch being at 0 unless we need to push to a channel repeatedly in a day (which I expect would be only if fixes are needed).

Having a version such as `1.230915.0` makes it easy to see when the release came out, and it naturally increments over time. If we make fixes to that channel that ships a week later, it'll just be version `1.230922.0`. We won't support patching old (minor) versions on a channel. Pick up the latest release if you want the latest fixes.

For releases pushed to the preview and stable channels, we'll tag the release branch with a tag that matches version number for easy correlation when investigating issues.  We'll not worry about tagging for nightly releases, as that seems like more tags/noise than value.

**Comment by minestarks** [comment]
> We'll avoid using pre-release semantics in versions (e.g. 1.10.1-beta). If you install from a pre-release channel, that should be obvious and intended. 

From context above, I understand "channel" to mean an entirely different package. Is there any precedence for this for pip packages? This seems like swimming against the current of established conventions, and I'm not sure I see a compelling enough reason to do it. As for some drawbacks - a consumer would be able to install the preview/nightly/stable packages side by side, which may create confusion. If a consumer wants to test their code against the upcoming preview, that's a code change on their part (rather than just a version bump). But minor drawbacks aside, why not follow convention?

**Comment by billti** [comment]
> If a consumer wants to test their code against the upcoming preview, that's a code change on their part (rather than just a version bump)

It's a change to 'pip install', but there code could remain the same, no? I believe any of the 3 pip packages could install the 'qsharp' module that the code would import from.

**Comment by minestarks** [comment]
>  just picked a few I know of at random and see the below examples:

The fact that there's precedence and an example we can follow makes me feel much better about this, thanks!

> What do you have in mind?

Oh what I had in mind was just the semver convention that I'm used to from other packages (e.g. most npm packages) - having only one package name, and using prerelease version tags for nightly and preview. This seems intuitive to me - what's the downside?

>  I believe any of the 3 pip packages could install the 'qsharp' module that the code would import from.

I believe you're correct. I was mistakenly assuming they'd declare different module names, I guess. In that case, I don't know what happens if the user accidentally installs both `qsharp-preview` and `qsharp` side by side, but it's probably not catastrophic.

**Comment by swernli** [comment]
I think this makes sense. While the date format is easy to read, it is not portable across all these requirements. We should also ensure that commit id is easily gettable from the published bits as an alternative way to identify a build, which already works for the playground but I don't think has been plumbed through the other packages yet.
