### ISSUE TITLE
`qsc_project`'s `get_manifest` API is not efficient

### ISSUE THREAD

**Issue by sezna** [microsoft/qsharp#929]
@minestarks and @idavis have context.

We have some areas where `get_manifest` is either called twice, or redundantly called. The language service should be updated to use the same `wasm.ProjectLoader` interface as the debugger, and we should remove the need to call `get_manifest` before constructing the project loader, since that takes in `getManifest` as well.

**Comment by minestarks** [comment]
I still think it's probably a good idea to call loadProject from the language service, but I wouldn't rush to do it since I kind of want to see how the code evolves. We're still fixing bugs and figuring things out and I'm not sure what exactly we need from the LS. I think we can close the issue though, it's a bit unactionable.
