### ISSUE TITLE
`onDidCloseTextDocument` not guaranteed to fire on closing visible text editor

### ISSUE THREAD

**Issue by sezna** [microsoft/qsharp#967]
The VS Code extension relies on `onDidCloseTextDocument` for its close document events, but this event is not guaranteed to fire if a buffer (text editor) is closed. We likely should be using [onDidChangeVisibleTextEditors](https://code.visualstudio.com/api/references/vscode-api#window.onDidChangeVisibleTextEditors).

**Comment by minestarks** [comment]
This problem seems to be made way worse by the fact that we [open a document](https://github.com/microsoft/qsharp/blob/cb7a7f5bbe5afbd9bc48a40df0d827e989a68860/vscode/src/diagnostics.ts#L45-L48) just to be able to show line/column offsets for any errors coming from it. If we open a document this way, VSCode seems to leave it open indefinitely.

It's pretty hard follow when this happens in actual usage, but basically the repro is:

- Have a project with `foo.qs` and `bar.qs`  where `bar.qs` contains errors.
- Open `foo.qs` (`bar.qs` should still be closed).
- Notice how we show errors for `bar.qs` in the Problems view (good).
- Now close `foo.qs`, and notice how the Problems never go away no matter how many times you open/close all of the files in the project. This is because `bar.qs` is "stuck" open.

If you manually open `bar.qs` first, this doesn't seem to be an issue.

Fixing #851 would address this, among a myriad of other problems.

**Comment by sezna** [comment]
I haven't seen this in a while, going to close this for now but will reopen if it becomes an issue again.
